In [5]:
import pickle
import numpy as np

In [3]:
ohe_sex = pickle.load(open('models/ohe_gen.pkl','rb'))
ohe_embark = pickle.load(open('models/embark.pkl','rb'))
model = pickle.load(open('models/model.pkl','rb'))

In [6]:
## Assume user input
## Pclass/gender/age/sibsp/parch,fare/embarked
test_input = np.array([2,'male','31.0',0,0,10.5,'S'],dtype=object).reshape(1,7)

In [7]:
test_input

array([[2, 'male', '31.0', 0, 0, 10.5, 'S']], dtype=object)

In [8]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [9]:
test_input_sex

array([[0., 1.]])

In [11]:
test_embark = ohe_embark.transform(test_input[:,5].reshape(1,1))

In [12]:
test_embark

array([[0., 0., 0.]])

In [13]:
test_input_age = test_input[:,2].reshape(1,1)

In [18]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_embark,test_input_sex),axis=1)

In [19]:
test_input_transformed.shape

(1, 10)

In [21]:
model.predict(test_input_transformed)

array([1], dtype=int64)