## 1. Accuracy = No of correct predictions/ Total Predictions

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/content/German_credit_data_aug.csv")

In [5]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad


In [6]:
df.drop(['Unnamed: 0','Sex','Housing','Saving accounts','Checking account','Purpose'],inplace=True,axis=1)

In [7]:
df.isnull().sum()

,0
Age,0
Job,0
Credit amount,0
Duration,0
Risk,0


In [8]:
df.dropna(inplace=True)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Risk'] = le.fit_transform(df['Risk'])

In [11]:
df.head()

,Age,Job,Credit amount,Duration,Risk
0,67,2,1169,6,1
1,22,2,5951,48,0
2,49,1,2096,12,1
3,45,2,7882,42,1
4,53,2,4870,24,0


In [12]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:5],df['Risk'],random_state=42,test_size=0.2)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [14]:
lor = LogisticRegression()
dt = DecisionTreeClassifier()

In [15]:
lor.fit(X_train,y_train)
dt.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [16]:
y_pred = lor.predict(X_test)
y_pred1 = dt.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [18]:
print(accuracy_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred1))

1.0
1.0


In [19]:
precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score(y_test, y_test)

NameError: name 'precision_score' is not defined

### Limitataion of Accuracy: Nature of errors is not known(TP,TN,FP,FN)

## 2. Confusion Matrix
#####1. TP,TN,FP,FN
#####2. Type 1 error and Type 2 error

In [ ]:
print(confusion_matrix(y_test,y_pred))

## Multiclass Confusion Matrix

In [22]:
df2 = pd.read_csv("/content/Iris (1).csv")
df2.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [23]:
X_train,X_test,y_train,y_test = train_test_split(df2.iloc[:,1:5],df2['Species'],random_state=42,test_size=0.2)

In [24]:
lor1 = LogisticRegression()
lor1.fit(X_train,y_train)

LogisticRegression()

In [25]:
y_pred3 = lor1.predict(X_test)

In [26]:
print(confusion_matrix(y_test,y_pred3))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [27]:
## D classes - mnist data
df3 = pd.read_csv("/content/train.csv")
df3.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [28]:
X_train,X_test,y_train,y_test = train_test_split(df3.iloc[:,1:],df3['label'],random_state=42,test_size=0.2)

In [29]:
lor2 = LogisticRegression()
lor2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
y_pred4 = lor2.predict(X_test)

In [31]:
pd.DataFrame(confusion_matrix(y_test,y_pred4),columns=range(0,10))

,0,1,2,3,4,5,6,7,8,9
0,787,0,2,2,3,13,6,1,2,0
1,0,887,6,0,1,4,1,2,7,1
2,5,12,758,13,9,9,11,8,20,1
3,2,3,26,831,0,24,1,9,25,16
4,5,1,5,1,779,1,11,3,5,28
5,7,2,7,25,8,610,18,2,20,3
6,7,1,6,0,3,7,754,1,5,1
7,0,2,6,12,13,2,1,819,6,32
8,4,11,8,28,6,25,6,4,738,5
9,7,3,2,12,20,8,0,28,7,751


In [32]:
precision_score(y_test,y_pred4,average=None)  ##for 10 different classes ke we got precison here

NameError: name 'precision_score' is not defined

In [ ]:
recall_score(y_test,y_pred4,average=None)  ##for 10 different classes ke we got recall here

In [ ]:
f1_score(y_test,y_pred4,average=None)  ##for 10 different classes ke we got f1 score here

In [ ]:
recall_score(y_test,y_pred4,average='macro')  ## single value

In [ ]:
## weighted
recall_score(y_test,y_pred4,average='weighted')

## Precision, Recall and F1 score

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [ ]:
precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score(y_test, y_test)

In [ ]:
precision_score(y_test, y_pred,average=None)

## Classification Report

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred4))  #support tells the no of ocurrence of that particular class

## 3. ROC-AUC Curve

In [20]:
data = pd.read_csv("/content/diabetes.csv")

In [44]:
X_test.shape

(154, 8)

In [21]:

data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data.iloc[:,0:8],data['Outcome'],random_state=42,test_size=0.2)

In [36]:
lor4 = LogisticRegression(max_iter=1000)

In [37]:
lor4.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [38]:
y_scores = lor4.predict_proba(X_test)[:,1]

In [39]:
y_scores

array([0.27587171, 0.18844086, 0.11448808, 0.16354446, 0.47152763,
       0.44181565, 0.01545949, 0.66077894, 0.54146137, 0.77733211,
       0.25591838, 0.89734144, 0.3362008 , 0.30303447, 0.08198096,
       0.38092464, 0.13935392, 0.07479528, 0.86674191, 0.56143057,
       0.20841338, 0.07739483, 0.53962428, 0.0945844 , 0.5394989 ,
       0.88554595, 0.12431327, 0.03016297, 0.25152958, 0.11581437,
       0.91112978, 0.87075938, 0.76536041, 0.83753319, 0.61668745,
       0.68328935, 0.96813003, 0.24363738, 0.51147551, 0.73613825,
       0.06983479, 0.59412645, 0.58366935, 0.32718599, 0.02759122,
       0.50239275, 0.6393479 , 0.22533799, 0.36056256, 0.95629563,
       0.04889599, 0.66096112, 0.8116769 , 0.24552928, 0.09325806,
       0.04152087, 0.7781665 , 0.0057039 , 0.40861817, 0.75696165,
       0.74134846, 0.35194245, 0.19236789, 0.20492144, 0.07688254,
       0.62716494, 0.0509161 , 0.7328617 , 0.03691982, 0.71593403,
       0.67523613, 0.07016495, 0.18115143, 0.11430304, 0.09115

In [41]:
from sklearn.metrics import roc_curve
fpr,tpr,thresholds = roc_curve(y_test,y_scores)

In [42]:
thresholds

array([       inf, 0.97115521, 0.96813003, 0.95629563, 0.90262249,
       0.89734144, 0.80096521, 0.7781665 , 0.77789864, 0.77733211,
       0.7328617 , 0.72427692, 0.68328935, 0.67523613, 0.66096112,
       0.66077894, 0.6555798 , 0.64967188, 0.6393479 , 0.61668745,
       0.60581059, 0.58366935, 0.55036457, 0.5394989 , 0.53417122,
       0.50297386, 0.50239275, 0.42044193, 0.42015964, 0.40861817,
       0.38092464, 0.33903877, 0.32718599, 0.30303447, 0.30268011,
       0.25731429, 0.24066279, 0.22533799, 0.2251495 , 0.20841338,
       0.20492144, 0.16354446, 0.14043101, 0.12822715, 0.12698331,
       0.11448808, 0.11430304, 0.04152087, 0.04047859, 0.00417295])

In [45]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [46]:
# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal threshold is:", optimal_threshold)

Optimal threshold is: 0.5503645724616164


## AUC

In [47]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Assuming that X_train, X_test, y_train, y_test are already defined

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()
